[project]
name = "duckify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tracing"
]

[tool.uv.workspace]
members = ["tracing"]

[tool.uv.sources]
tracing = { workspace = true }
